### ISSUE TITLE
poor docs

### ISSUE THREAD

**Issue by kotchuprik** [frostealth/yii2-aws-s3#1]
do you can describe more of your examples? because upload() is return some data but docs doesn't has any info about it.

**Comment by Ma-ve** [comment]
Don't use `upload()`: upload literally puts the name you gave the file (example.txt, photo.jpg), with the content of the url. Use `put`, with the `fopen` command, as shown in the first example.

**Comment by frostealth** [comment]
`upload` returns [`Aws\ResultInterface`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.ResultInterface.html), see more in [official doc](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#_upload).

@Ma-ve you can use `upload` with the `Psr\Http\Message\StreamInterface`, php stream resource, or a string of data to upload.

**Comment by frostealth** [comment]
Added [API](https://github.com/frostealth/yii2-aws-s3/blob/master/API.md).
