### ISSUE TITLE
GetPresignedCdnUrl()

### ISSUE THREAD

**Issue by iadj** [frostealth/yii2-aws-s3#10]
Since we have `getUrl` and `getCdnUrl`, I think it'd be logical if we have a CDN equivalent function for `getPresignedUrl` (i.e. `getPresignedCdnUrl`).

This page explains how to use `Aws\CloudFront\CloudFrontClient` to generate signed CloudFront URLs:
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/cloudfront-signed-url.html

**Comment by frostealth** [comment]
It's a duplicate #9
