### ISSUE TITLE
Requires PHP7

### ISSUE THREAD

**Issue by newscloud** [frostealth/yii2-aws-s3#11]
Cool library. Lots of potential.

I received this error. Do you really need PHP7 for this? I was unable to install with satisfiable names below.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - frostealth/yii2-aws-s3 v2.0.0-beta.1 requires php >=7.0.0 -> your PHP version (5.6.10) does not satisfy that requirement.
    - frostealth/yii2-aws-s3 v2.0.0-beta requires php >=7.0.0 -> your PHP version (5.6.10) does not satisfy that requirement.
    - Installation request for frostealth/yii2-aws-s3 ~2.0.0@beta -> satisfiable by frostealth/yii2-aws-s3[v2.0.0-beta, v2.0.0-beta.1].

**Comment by frostealth** [comment]
There are used scalar type hinting, return type declarations and null coalescing operator.
Why don't you update to the latest version?

**Comment by davidjeddy** [comment]
@frostealth Large scale application take months to years to update the under lying architecture.

@newscloud Recommend using the v1 version. As per semver when the first place digit changes that means backwards breaking changes. PHP5 -> 7 BC changes. yii2-aws-s3 1.x -> 2.x : BC changes. I feel your pain as v2 has some nice changes but the system this is being used on is only PHP 5.6.

**Comment by frostealth** [comment]
@davidjeddy thank you for your detailed answer for @newscloud 👍

**Comment by frostealth** [comment]
@newscloud I agree with @davidjeddy and also recommend you to use the first version for your projects with php5.

**Comment by newscloud** [comment]
@davidjeddy thanks. what's the version number for v1? or is it in a different repo? I don't see it clearly.

**Comment by davidjeddy** [comment]
@newscloud Here you go: 
![screen shot 2016-04-14 at 13 19 39](https://cloud.githubusercontent.com/assets/6232455/14537102/92a73fea-0243-11e6-9ae4-b8d9590747f9.png)

**Comment by frostealth** [comment]
@newscloud v1.0.0 on [packagist](https://packagist.org/packages/frostealth/yii2-aws-s3#v1.0.0) and in this [repo](https://github.com/frostealth/yii2-aws-s3/tree/1.x).

**Comment by newscloud** [comment]
Got it! Thank you!

On Thu, Apr 14, 2016 at 10:20 AM, Ivan Kudinov notifications@github.com
wrote:

> @newscloud https://github.com/newscloud v1.0.0 on packagist
> https://packagist.org/packages/frostealth/yii2-aws-s3#v1.0.0 and in
> this repo https://github.com/frostealth/yii2-aws-s3/tree/1.x.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/frostealth/yii2-aws-s3/issues/11#issuecomment-210059087

## 

Jeff Reifman
http://lookahead.io
http://jeffreifman.com
