### ISSUE TITLE
Enhancement (v1): Set content-type using upload()

### ISSUE THREAD

**Issue by davidjeddy** [frostealth/yii2-aws-s3#12]
Usage

```
            \Yii::$app->get('s3bucket')->upload(
                $filename,
                $this->file->tempName,
                \Yii::$app->get('s3bucket')->defaultAcl,
                [
                    'ContentType'        => $this->file->type,
                    'ContentDisposition' => 'render',
                ]
            );
```

Expected: file would be of defined content-type in the S3 bucket.
Actual: file is octet-stream in S3 bucket

Tried: 

```
            \Yii::$app->get('s3bucket')->put(
                $filename,
                $this->file->tempName,
                \Yii::$app->get('s3bucket')->defaultAcl,
                [
                    'ContentType'        => $this->file->type,
                    'ContentDisposition' => 'render',
                ]
            );
...and...
            \Yii::$app->get('s3bucket')->put(
                $filename,
                fopen($this->file->tempName, 'r+'),
                \Yii::$app->get('s3bucket')->defaultAcl,
                [
                    'ContentType'        => $this->file->type,
                    'ContentDisposition' => 'render',
                ]
            );
...and...
            \Yii::$app->get('s3bucket')->upload(
                $filename,
                fopen($this->file->tempName, 'r+'),
                \Yii::$app->get('s3bucket')->defaultAcl,
                [
                    'ContentType'        => $this->file->type,
                    'ContentDisposition' => 'render',
                ]
            );
```

**Comment by frostealth** [comment]
What version `aws-sdk-php` you have installed?
Do you have the same problem if you use `put` method?

I think the problem is in `aws-sdk-php`.
The `Aws\S3\MultipartUploader` detects and overwrites mime-type of the file by its extension.
You can see it [here](https://github.com/aws/aws-sdk-php/blob/3.17.6/src/S3/MultipartUploadingTrait.php#L100) and [here](https://github.com/aws/aws-sdk-php/blob/3.17.6/src/S3/MultipartUploader.php#L118).

Do you have any suggestions for solving this problem?

**Comment by davidjeddy** [comment]
- aws-sdk-php as is required by the library (nothing else currently using it).
- Using PUT the resulting content on S3 is 14bytes (corrupt data).
- Ooooo, ok. That explains a lot; our logic right now uses the PHP temp file in /tmp/\* as the source file to upload as we do not want to save the file to disk before pushing it to S3. Solution may be that we will have to save it to disk, upload it, then delete one our machine. Suggestions?

**Comment by frostealth** [comment]
There is the same problem on [stackoverflow](http://stackoverflow.com/questions/9182662/amazon-s3-files-uploaded-using-aws-sdk-for-php-is-always-application-octet-stre)

The code is from a project that works without any problems:

``` php
$file = UploadedFile::getInstanceByName('image');
// ...
$body = file_get_contents($file->tempName);
$storage->put($filename, $body, null, [
    'ContentType' => $file->type,
]);
```

**Comment by davidjeddy** [comment]
Hazzah! That helped out greatly! Final solution:

```
            if (!($this->file instanceof \yii\web\UploadedFile)) { return false; }

            $filename = \Yii::$app->S3->path(\Yii::$app) . \Ramsey\Uuid\Uuid::uuid4()->toString() . '.' . explode('/', $this->file->type)[1];

            \Yii::$app->get('s3bucket')->put(
                $filename,
                file_get_contents($this->file->tempName),
                \Yii::$app->get('s3bucket')->defaultAcl,
                [
                    'ContentType' => $this->file->type,
                ]
            );

            return ($filename ?: false);
```
