### ISSUE TITLE
Обратная совместимость с PHP 5.*

### ISSUE THREAD

**Issue by mxkh** [frostealth/yii2-aws-s3#13]
Возможна ли обратная совместимость со старыми версиями PHP ? 5.6 например. 

Наш проект использует Ваш extension и мы на данный момент не можем обновить версию PHP до 7-й.

**Comment by chuprik** [comment]
@mxkh ребята, ну что ж вы такие невнимательные :)

https://packagist.org/packages/frostealth/yii2-aws-s3#v1.0.0 раз
https://github.com/frostealth/yii2-aws-s3/releases/tag/v1.0.0 два
https://github.com/frostealth/yii2-aws-s3/tree/1.x три

Никогда не используйте `*` в версии пакета и будет вам счастье. Только стабильную версию, которая доступна на packagist. Composer умеет такое и этим нужно пользоваться

**Comment by frostealth** [comment]
Обратная совместимость между мажорными версиями не предусматривается, [подробнее про semantic versioning](http://semver.org/lang/ru/)
Вы можете продолжать пользоваться первой версией, указав в зависимостях версию `~1.0`.

Рекомендую в зависимостях всегда указывать конкретную мажорную версию как минимум.
