### ISSUE TITLE
How to use a mock server?

### ISSUE THREAD

**Issue by AnujaLK** [frostealth/yii2-aws-s3#14]
Please explain the feasibility of using a mock service with your library. We have a requirement to test our yii2 application locally without uploading files to s3.

**Comment by davidjeddy** [comment]
That really wouldn't be possible with this library, basically asking 'how to test uploading files without uploading files'. However, the solution my org does is setup a test bucket that is cleared on demand. Then in our .env we set the bucket name.

**Comment by chuprik** [comment]
hey guys, could you show some examples of mock service for services like s3?
