### ISSUE TITLE
composer.json configuration

### ISSUE THREAD

**Issue by claudioferrari** [frostealth/yii2-aws-s3#18]
Hello,
if I add "frostealth/yii2-aws-s3": "~2.0@rc" to my composer.json I can't find the package.

Any suggestion?

Thanks

**Comment by chuprik** [comment]
Hi, could you look https://getcomposer.org/doc/04-schema.md#minimum-stability ?

**Comment by frostealth** [comment]
Hello. Could you show the console log and your `composer.json`?
I've no problems with installing via the command `composer require frostealth/yii2-aws-s3 ~2.0@rc` even with `"minimum-stability": "stable"` in my `composer.json` file.

**Comment by frostealth** [comment]
@claudioferrari is the problem still relevant?
