### ISSUE TITLE
I am getting SSL certificate problem

### ISSUE THREAD

**Issue by RamzyVirani** [frostealth/yii2-aws-s3#19]
Hi, 
I am getting below error on Windows + XAMPP environment. 
**AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)**

I am using v1 for PHP 5.6

Thanks.

**Comment by frostealth** [comment]
Hello.
http://stackoverflow.com/questions/24620393/aws-ssl-security-error-curl-60-ssl-certificate-prob-unable-to-get-local

**Comment by nagaokashi** [comment]
Hi, double issue.
I tried solutions as above link but not work.
To clarify . How to solve in Version 2?
