### ISSUE TITLE
Default Region

### ISSUE THREAD

**Issue by ctala** [frostealth/yii2-aws-s3#2]
The default region follows the folling path : s3.amazonaws.com and the different regions : s3-<region>.amazonaws.com

So, for example if you create a client by specifying the eu-west-1 region, it maps to the following region-specific endpoint:

s3-eu-west-1.amazonaws.com

Actually the default address is not being managed and the other endpoints follows the end point like : s3.ENDPOINT.amazonaws.com that should be not the standard according to docs.

**Comment by frostealth** [comment]
I don't understand what you want to say or offer.

If you want to change the endpoint, you can do this using the options property:
```php
'components' => [
    's3Bucket' => [
        'class' => '\frostealth\yii2\aws\s3\Storage',
        // ...
       'options' => ['endpoint' => 'the full uri of the webservice'],
    ],
],
```

The S3Client doesn't use the default region.
