### ISSUE TITLE
Use custom CNAME for bucket

### ISSUE THREAD

**Issue by ghost** [frostealth/yii2-aws-s3#20]
Hi!

I have my bucket on S3 and default URL is **https://s3-*region*.amazonaws.com**.

If I have an CNAME record to point that bucket, can I set my custom CNAME to get the bucket content.

I.E: **http://mybucket.mydomain.com** instead of **_https://s3-*region*.amazonaws.com_**

Thanks!

**Comment by frostealth** [comment]
Hello.
You can configure `S3Client` with `options` for v1 and `clientConfig` for v2.
For more information see [the official sdk](https://github.com/aws/aws-sdk-php).
