### ISSUE TITLE
Package doesn't install even though I have PHP 7.0

### ISSUE THREAD

**Issue by iadj** [frostealth/yii2-aws-s3#21]
Please don't hard require PHP 7.0 in the package requirements. I'm running >=7.0 in production and the package update broke my app until I reverted this package to use ~1.0.

**Comment by frostealth** [comment]
I don't understand your problem. Would you describe the problem in detail?

**Comment by frostealth** [comment]
The package doesn't work on php version below 7.0.

I can assume that you're using "*" in the version of the package. If so, I don't recommend to do that.
As per [SemVer](http://semver.org/) when the first place digit changes that mean backwards breaking changes.
