### ISSUE TITLE
How can I get list of files?

### ISSUE THREAD

**Issue by jukuan** [frostealth/yii2-aws-s3#22]
Hi.
Thanks for your component.
Everything is fine and pretty simple. But I have a question about getting list of object. This simple operation looks not obvious.

Have I understood it correctly, I should make custom command class, handler for it and run something like lines bellow?

```
class CustomCommand implements Command, HasBucket
{}

class CustomCommandHandler extends Handler
{}

$command = $s3->create(CustomCommand::class);
$result = $s3->execute($command);
```

Thanks in advance.

**Comment by jukuan** [comment]
UPD.

So. I managed get items using custom plain command without handler.

```
class MyPlainCommand implements PlainCommand, HasBucket {
    public function getName(): string
    {
        return 'ListObjects';
    }
}
```

**Comment by frostealth** [comment]
Hi.

Yes, custom `PlainCommand` is a nice solution.

Thank you for your feedback.
