### ISSUE TITLE
  Undefined property: Fxp\Composer\AssetPlugin\Repository\BowerRepository::$repoConfig

### ISSUE THREAD

**Issue by shahidkarimi** [frostealth/yii2-aws-s3#23]
`D:\wamp64\www\fpv1>composer require frostealth/yii2-aws-s3 ~2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [ErrorException]
  Undefined property: Fxp\Composer\AssetPlugin\Repository\BowerRepository::$repoConfig

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...`

**Comment by frostealth** [comment]
It`s a conflict of versions of composer and asset-plugin.

You need update composer and asset-plugin.

**Comment by hovannes-fonq** [comment]
requiring the asset-plugin worked for me.
`composer global require fxp/composer-asset-plugin --no-plugins`

**Comment by ShokirjonMK** [comment]
php composer.phar global update fxp/composer-asset-plugin --no-plugins
