### ISSUE TITLE
Error executing "GetObject" on "https://s3.u

### ISSUE THREAD

**Issue by shahidkarimi** [frostealth/yii2-aws-s3#25]
`Error executing "GetObject" on "https://s3.us-east-23.amazonaws.com/t-ert-34-infra-5dgdfrg/1488396616.jpeg"; AWS HTTP error: Client error: `GET https://s3.us-east-23.amazonaws.com/t-ert-34-infra-5dgdfrg/1488396616.jpeg` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...)
NoSuchKey (client): The specified key does not exist. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>1488396616.jpeg</Key><RequestId>04407CDF4F0C239B</RequestId><HostId>Rlwa7GT13kzYCEZKPIEHkfOXXmRj19loc6rZnVt9FnoQO6dq1kAQtJneIrOYVTqsAgT/uWMiTWY=</HostId></Error>`

**Comment by frostealth** [comment]
@shahidkarimi Maybe this file doesn't exist?

[404 Http Status Code](https://en.wikipedia.org/wiki/HTTP_404)
