### ISSUE TITLE
PHP Parse Error – yii\base\ErrorException  syntax error, unexpected '?'

### ISSUE THREAD

**Issue by rmdganesan** [frostealth/yii2-aws-s3#28]
1. in D:\Work\v2newrepo\vendor\frostealth\yii2-aws-s3\src\Service.php at line 64

foreach ($this->defaultComponentDefinitions() as $name => $definition) {
            $this->components[$name] = $this->components[$name] ?? $definition;
        }
below my configuration

's3' => [
            'class' => 'frostealth\yii2\aws\s3\Service',
            'credentials' => [ // Aws\Credentials\CredentialsInterface|array|callable
                'key' => 'xxxxxxxxxxxxxxxxxxxxxxx',
                'secret' => 'xxxxxxxxxxxxxxxxxxxx',
            ],
            'region' => 'ap-south-1',
            'version' => 'latest',
            'defaultBucket' => 'test',
            'defaultAcl' => 'public-read',
        ],

**Comment by chuprik** [comment]
1) what version of PHP?
2) could you show full error details?

**Comment by rmdganesan** [comment]
PHP Version 5.6.21

![image](https://cloud.githubusercontent.com/assets/7314661/26037870/9496f102-3905-11e7-9f1b-14dea4caf4e0.png)

i just create object: 

$s3 = Yii::$app->get('s3');

**Comment by chuprik** [comment]
How did you install the package? Min version of PHP is 7.0

![image](https://cloud.githubusercontent.com/assets/802946/26037920/fce2b5aa-38fd-11e7-8893-9acb39016302.png)

**Comment by frostealth** [comment]
The package of the latest version requires PHP >= 7.0.
For PHP 5.6 use [version 1.0](https://github.com/frostealth/yii2-aws-s3/tree/1.x).

**Comment by enkhtulga** [comment]
For PHP 5.4.16, i used [version 0.2.0](https://github.com/frostealth/yii2-aws-s3/tree/v0.2.0). Unfortunately, i cannot upload. please help me.
