### ISSUE TITLE
uploadAsync not working

### ISSUE THREAD

**Issue by CCSS-Github** [frostealth/yii2-aws-s3#3]
Earlier we are using mulitpart form upload which is going to be deprecate. So we switch to UploadAsync method to upload image to S3 but its creating empty file with no content - image file only have source file path in it. Kindly guide

**Comment by CCSS-Github** [comment]
Sample code:

				// checking valid local path
				if (!file_exists($local_file_url)) array("error"=>"invlid_path");
		
				// TODO: Bucket configuration as per environment
				$bucket = '';
		
				// image upload settings
				$concurrency = 5;
				$minPartSize = 1073741824; // 1024 MB
				
				// image upload aws
				// Yii::$app->get(S3_BUCKET)->multipartUpload(
					// "$desired_aws_url",
					// "$local_file_url",
					// $concurrency,
					// $minPartSize
				// );
			

				$promise = Yii::$app->get(S3_BUCKET)->uploadAsync(
					"$desired_aws_url",
					"$local_file_url",
					$concurrency,
					$minPartSize
				);

				
				
				// block until the result is ready
				$promise->wait();
				print_r($promise); exit;
			
			
			// Getting image absolute path from aws	
			$aws_url = Yii::$app->get(S3_BUCKET)->getUrl("$desired_aws_url");

			return $aws_url;

**Comment by frostealth** [comment]
Try 
```php
$promise = Yii::$app->get('bucket')->getClient()->uploadAsync(
    $bucket, 
    $filename, 
    $source, 
    $acl, 
    ['concurrency' => 5, 'part_size' => 1073741824]
);
```

The problem remains?

**Comment by cozumel424** [comment]
I just had the same issue, the second solution works ok, thanks!
