### ISSUE TITLE
Compatibility with php 7.2

### ISSUE THREAD

**Issue by Simutin32** [frostealth/yii2-aws-s3#31]
PHP Compile Error 'yii\base\ErrorException' with message 'Cannot use yii\base\Object as Object because 'Object' is a special class name' 

in ../vendor/frostealth/yii2-aws-s3/src/HandlerResolver.php:9

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

As sujesting yii2 team in upgrade note:
"For extensions that have classes extending from `yii\base\Object`, to be compatible with PHP 7.2, you need to require `"yiisoft/yii2": "~2.0.13"` in composer.json and change affected classes to extend from `yii\base\BaseObject` instead. It is not possible to allow Yii versions `<2.0.13` and be compatible with PHP 7.2 or higher."

**Comment by frostealth** [comment]
Fixed. Thanks for your issue
