### ISSUE TITLE
Setting file properties (content-type, content-disposition etc.)

### ISSUE THREAD

**Issue by iadj** [frostealth/yii2-aws-s3#4]
How do you set `content-type` and `content-disposition`, and permissions with `put()`?

**Comment by frostealth** [comment]
```php
Yii:$app->get('s3bucket')->upload(
    $filename,
    $source,
    $acl,
    [
        'params' => [
            'ContentType' => $type,
            'ContentDisposition' => $disposition,
        ],
    ]
);
```

**Comment by frostealth** [comment]
@iadj the issue is relevant?

**Comment by iadj** [comment]
@frostealth Tried it but it didn't seem to work. I'm now setting the headers using  `header('Content-Type: ' . $contentType)`  before downloading the file using `header('Location: ' . $location)`. I'll try again with your method and will get back at you with results.

**Comment by frostealth** [comment]
Apparently, the issue isn't relevant. Close.
