### ISSUE TITLE
Can't upload and then unlink.

### ISSUE THREAD

**Issue by bryantmakesprog** [frostealth/yii2-aws-s3#8]
To reproduce:

```
Yii::$app->get('s3bucket')->upload($toFile, $fromFile);
unlink($fromFile);
```

Uploading works by itself. Unlinking works by itself. But I can't upload and then unlink. I get "Permission Denied".

**Comment by frostealth** [comment]
I can't reproduce.
Have you tried to use `put()`?

**Comment by bryantmakesprog** [comment]
I ended up fixing it by running garbage collection between the upload and the unlink. I don't think it was a problem with your library.

On Mar 1, 2016, at 8:07 AM, Ivan Kudinov <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce.
Have you tried to use put()?

-

**Comment by frostealth** [comment]
I'm glad the problem was resolved.
