### ISSUE TITLE
Invalidate Object

### ISSUE THREAD

**Issue by iadj** [frostealth/yii2-aws-s3#9]
If CloudFront CDN is configured, we should have the ability to invalidate an object so that it clears from the CloudFront cache (maybe automatically if a file is being overwritten): http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

**Comment by frostealth** [comment]
Could you give me an example of usage on the client side, please?

**Comment by iadj** [comment]
@frostealth When we use S3 for uploading avatars for instance, it's a plausible process for the app to save the avatar as `<user_id>.jpg'. If the user then uploads a new avatar, it will be uploaded to S3 with the same file name. CloudFront should invalidate the file object so it represents the new file in the cache, so that when the file is served from CloudFront it displays the new file instead of the old one.

Here's a PHP package that lets you invalidate objects: https://github.com/subchild/CloudFront-PHP-Invalidator/blob/master/CloudFront.php

**Comment by frostealth** [comment]
Thank you.
I think it should be a separate component/wrapper

**Comment by iadj** [comment]
@frostealth Alright. I'll look into it.
What about the `getPresignedCdnUrl()` function? It would be quite useful for people who want to use presigned URLs with CloudFront.

**Comment by frostealth** [comment]
`getPresignedCdnUrl()` has to use the instance of `Aws\CloudFront\CloudFrontClient` and should be in the `CloudFrontClient` wrapper.
See [`Aws\CloudFront\CloudFrontClient::getSignedUrl()`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CloudFront.CloudFrontClient.html#_getSignedUrl).

**Comment by frostealth** [comment]
I think the idea of combining multiple clients into one wrapper is bad.

You can write your own simple `CloudFrontClient` wrapper or use a third-party.
It will be the right way 👍

Thank you for your issue.
